# Simple Neural Network:

In [ ]:
# Create Model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features) # basically calculating z=wx+b
    out = self.sigmoid(out)
    return out




In [ ]:
# create dataset
features = torch.rand(10,5)

# create model, basically creating an object of the class
model = Model(features.shape[1])

# Call model for forward pass
model(features) # here, we can also write "model.forward(features)"

tensor([[0.5274],
        [0.5528],
        [0.5399],
        [0.5051],
        [0.5691],
        [0.5406],
        [0.5108],
        [0.6043],
        [0.6073],
        [0.6122]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.0855,  0.3900, -0.2995,  0.1971, -0.0338]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.1488], requires_grad=True)

In [ ]:
pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Neural Network with one hidden layer:

In [ ]:
# Creating neural network model with hidden layer
# Create Model Class
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [ ]:
# create dataset
features = torch.rand(10,5)

# Create model
model = Model(features.shape[1])

# Call forward pass
model(features)

tensor([[0.3576],
        [0.3455],
        [0.3281],
        [0.3462],
        [0.2722],
        [0.3899],
        [0.3257],
        [0.2997],
        [0.3291],
        [0.3005]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[ 0.1219,  0.2185, -0.1982,  0.2845,  0.1996],
        [ 0.2152,  0.1899, -0.1630,  0.2301,  0.3766],
        [ 0.2435, -0.1654, -0.2789,  0.1971,  0.0505]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.0291,  0.1077,  0.1714], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[-0.5034, -0.1268, -0.4287]], requires_grad=True)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([-0.4010], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using Sequential Container:

In [ ]:
# Creating neural network model with hidden layer
# Create Model Class
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [ ]:
# create dataset
features = torch.rand(10,5)

# Create model
model = Model(features.shape[1])

# Call forward pass
model(features)

tensor([[0.4891],
        [0.4988],
        [0.4747],
        [0.4904],
        [0.5001],
        [0.4959],
        [0.5012],
        [0.4764],
        [0.4961],
        [0.4840]], grad_fn=<SigmoidBackward0>)