In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f'Using GPU: {torch.cuda.get_device_name(0)}')
else:
    print("GPU is not available. Using CPU")

GPU is available
Using GPU: Tesla T4


# Creating a Tensor:

In [ ]:
# using empty(allocate memory)
a = torch.empty(2,3)
print(a)

tensor([[1.1479e-41, 0.0000e+00, 7.2868e-43],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
b = torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# using ones
c = torch.ones(2,3)
print(c)


tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.4374, 0.6976, 0.6829],
        [0.0990, 0.0712, 0.7179]])

In [ ]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# using arange
print(torch.arange(1,10,2))

# using linspace
print(torch.linspace(1,10,5))

# using eyes
print(torch.eye(3))

# using full
print(torch.full((2,3),2))

tensor([1, 3, 5, 7, 9])
tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[2, 2, 2],
        [2, 2, 2]])


# Tensor Shapes:

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x.shape)

torch.Size([2, 3])


In [ ]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6066685342724992309, 3977023928965674288, 6499874266848638510]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Datatypes:

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign datatype
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
# using to
x.to(torch.float)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Scalar Operations:

In [ ]:
x = torch.rand(2,2)
x
# addition
print(x+2)
# subtraction
print(x-2)
# multiplication
print(x*2)
# division
print(x/2)
# int division
print(x//2)
# mod
print(x%2)
# power
print(x**2)

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])
tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])
tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


# Element wise Operations:

In [ ]:
a = torch.rand(2,3)
print(a)
b = torch.rand(2,3)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
# addition
print(a+b)
# subtraction
print(a-b)
# multiplication
print(a*b)
# division
print(a/b)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])
tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])
tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])


In [ ]:
c = torch.tensor([-1,2,3,-4])
# absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.negative(c)

tensor([ 1, -2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 3.4, 6.7, 8.2])

In [ ]:
# round
torch.round(d)

tensor([2., 3., 7., 8.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 4., 7., 9.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 3., 6., 8.])

In [ ]:
# clamp
torch.clamp(d, min=3, max=6)

tensor([3.0000, 3.4000, 6.0000, 6.0000])

# Reduction Operations:

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10)
print(e)

tensor([[8, 0, 7],
        [0, 0, 9]])


In [ ]:
# sum
print(torch.sum(e))
# sum across columns
print(torch.sum(e, dim=0))
# sum across rows
print(torch.sum(e, dim=1))

tensor(24)
tensor([ 8,  0, 16])
tensor([15,  9])


In [ ]:
# mean
print(torch.mean(e, dtype=float))
# mean across columns
print(torch.mean(e, dim=0, dtype=float))
# mean across rows
print(torch.mean(e, dim=1, dtype= float))

tensor(4., dtype=torch.float64)
tensor([4., 0., 8.], dtype=torch.float64)
tensor([5., 3.], dtype=torch.float64)


In [ ]:
# median
print(torch.median(e))
# median across columns
print(torch.median(e, dim=0))
# median across rows
print(torch.median(e, dim=1))

tensor(0)
torch.return_types.median(
values=tensor([0, 0, 7]),
indices=tensor([1, 0, 0]))
torch.return_types.median(
values=tensor([7, 0]),
indices=tensor([2, 1]))


In [ ]:
# max and min
print(torch.max(e))
print(torch.min(e))


tensor(9)
tensor(0)


In [ ]:
# prod
print(torch.prod(e))
# prod across columns
print(torch.prod(e, dim=0))
# prod across rows
print(torch.prod(e, dim=1))

tensor(0)
tensor([ 0,  0, 63])
tensor([0, 0])


In [ ]:
torch.std(e.float())

tensor(4.4272)

In [ ]:
# variance
torch.var(e.float())

tensor(19.6000)

In [ ]:
# argmax
torch.argmax(e)

tensor(5)

In [ ]:
# agrmin
torch.argmin(e)

tensor(1)

# Matrix Operation:

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
print(f)
g = torch.randint(size=(3,2), low=0, high=10)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [ ]:
# matrix multiplication
print(torch.matmul(f,g))


tensor([[ 87, 119],
        [ 65,  99]])


In [ ]:
a= torch.tensor([1,2])
b= torch.tensor([3,4])

# dot product
print(torch.dot(a,b))

tensor(11)


In [ ]:
# transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10)
print(h)

tensor([[5, 9, 8],
        [9, 7, 9],
        [2, 6, 7]])


In [ ]:
# determinant
torch.det(h.float())

tensor(-110.)

In [ ]:
# inverse
torch.inverse(h.float())

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

# Comparison Operations:

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
print(i)
j = torch.randint(size=(2,3), low=0, high=10)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [ ]:
# greater than
print(i>j)
# less than
print(i<j)
# equal to
print(i==j)
# not equal to
print(i!=j)
# greater than equal to
print(i>=j)
# less than equal to
print(i<=j)

tensor([[ True,  True, False],
        [ True, False, False]])
tensor([[False, False,  True],
        [False,  True,  True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[ True,  True, False],
        [ True, False, False]])
tensor([[False, False,  True],
        [False,  True,  True]])


# Special Functions:

In [ ]:
k= torch.randint(size=(2,3), low=0, high=10)
print(k)

tensor([[3, 3, 5],
        [0, 6, 4]])


In [ ]:
# log
torch.log(k.float())

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [ ]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [ ]:
# sqrt
torch.sqrt(k.float())

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [ ]:
# sigmoid
torch.sigmoid(k.float())

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [ ]:
# softmax
torch.softmax(k.float(), dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [ ]:
# relu
torch.relu(k.float())

tensor([[3., 3., 5.],
        [0., 6., 4.]])

# Inplace operations:

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [ ]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [ ]:
m


tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [ ]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

# Copying a tensor:

In [ ]:
a = torch.rand(2,3)
print(a)


tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [ ]:
b=a
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
a[0][0]= 0
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
id(a)

140556191406096

In [ ]:
id(b)

140556191406096

In [ ]:
b=a.clone()

In [ ]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
id(a)

140556191406096

In [ ]:
id(b)

140556191411936

In [ ]:
a[0][0]=10
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [ ]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
id(a)

140556191406096

In [ ]:
id(b)

140556191411936

# Tensor operations on GPU:

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device= torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
a = torch.rand((2,3), device=device)
a

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [ ]:
b=a.to(device)

In [ ]:
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]], device='cuda:0')

In [ ]:
b+5

tensor([[5.2243, 5.8935, 5.0497],
        [5.1780, 5.3011, 5.1893]], device='cuda:0')

In [ ]:
import time
size=10000
#create random matrix on CPU
a=torch.randn(size,size)
b=torch.randn(size,size)

# Measure time on CPU
start=time.time()
c=torch.matmul(a,b)
end=time.time()
y=end-start
print(y)

# move matrix to GPU
c=a.to(device=device)
d=b.to(device=device)

# measure time on GPU
start=time.time()
e=torch.matmul(c,d)
end=time.time()
x=end-start
print(x)
# compare results
print("CPU time/GPU time: ", y/x)

24.107835292816162
0.1268784999847412
CPU time/GPU time:  190.00725336219645


# Reshaping Tensors:

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)


tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.8881, 0.7989, 0.9514, 0.0141],
         [0.8903, 0.1649, 0.3162, 0.1331],
         [0.6763, 0.4254, 0.2375, 0.5430]],

        [[0.1174, 0.6532, 0.5115, 0.3094],
         [0.7907, 0.7351, 0.2693, 0.8009],
         [0.5839, 0.0061, 0.4671, 0.8243]]])

In [ ]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze
c=torch.rand(266,266,3)
c.unsqueeze(0).shape

torch.Size([1, 266, 266, 3])

In [ ]:
# squeeze
d=torch.rand(1,20)
d.unsqueeze(0).shape

torch.Size([1, 1, 20])

# NumPy and PyTorch:

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3,4])
a

tensor([1, 2, 3, 4])

In [ ]:
b=a.numpy()
b

array([1, 2, 3, 4])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c=np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [ ]:
d= torch.from_numpy(c)
d

tensor([1, 2, 3, 4])